# example: https://github.com/prometheus/alertmanager/blob/master/doc/examples/simple.yml
global:
  resolve_timeout: 5m

templates:
  - templates/*.tmpl

route:
  receiver: 'default-receiver'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  group_by: [cluster, alertname]
  # All alerts that do not match the following child routes
  # will remain at the root node and be dispatched to 'default-receiver'.
  routes:
  # All alerts with service=mysql or service=cassandra
  # are dispatched to the database pager.
  - receiver: 'email'
    group_wait: 10s
    match_re:
      service: mysql|cassandra
  # All alerts with the team=frontend label match this sub-route.
  # They are grouped by product and environment rather than cluster
  # and alertname.
  - receiver: 'email'
    group_by: [product, environment]
    match:
      team: frontend

receivers:
  - name: 'slack'
    slack_configs:
      - send_resolved: true
        username: '<username>'
        channel: '#<channel-name>'
        api_url: '<incomming-webhook-url>'
        color: <tmpl_string> | default = '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
        username: <tmpl_string> | default = '{{ template "slack.default.username" . }}'
        title: <tmpl_string> | default = '{{ template "slack.default.title" . }}'
        title_link: <tmpl_string> | default = '{{ template "slack.default.titlelink" . }}'

  - name: 'email'
    email_configs:
      - send_resolved: true
        to: <tmpl_string>
        from: <tmpl_string> | default = global.smtp_from
        smarthost: <string> | default = global.smtp_smarthost
        auth_username: <string>
        auth_password: <secret>
        auth_secret: <secret>
        auth_identity: <string>
        require_tls: <bool> | default = global.smtp_require_tls
        html: <tmpl_string> | default = '{{ template "email.default.html" . }}'

  - name: 'default-receiver'
    email_configs:
      - send_resolved: true
        to: <tmpl_string>
        from: <tmpl_string> | default = global.smtp_from
        smarthost: <string> | default = global.smtp_smarthost
        auth_username: <string>
        auth_password: <secret>
        auth_secret: <secret>
        auth_identity: <string>
        require_tls: <bool> | default = global.smtp_require_tls
        html: <tmpl_string> | default = '{{ template "email.default.html" . }}'
